server:
  port: 8000
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "https://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT